/**
 * The customization surface: everything a creator can change with one click.
 *
 * Each option resolves to a small set of CSS custom properties that the bake
 * step writes onto the composition root as an inline style. Templates consume
 * `var(--t-*)` with their own defaults as fallback, so an un-themed spec still
 * renders exactly as the style was designed.
 *
 * Options are frozen sets, deliberately. Free-form colour pickers produce
 * unreadable shorts in unpracticed hands; a curated palette cannot be made
 * illegible, which is the same reasoning as the frozen templates themselves.
 */

import { DOODLE_DATA } from './doodles.generated';

export interface PaletteOption {
  id: string;
  label: string;
  /** Page ground. */
  bg: string;
  /** Primary text. */
  ink: string;
  /** Secondary text (captions at rest). */
  soft: string;
  /** The single accent (rules, active caption word, reference bar). */
  accent: string;
  /** True when the ground is dark, so templates can flip grain/shadow logic. */
  dark: boolean;
}

export const PALETTES: readonly PaletteOption[] = [
  { id: 'parchment', label: 'Parchment', bg: '#f6f1e7', ink: '#221e19', soft: '#6b6157', accent: '#b4552e', dark: false },
  { id: 'ivory-navy', label: 'Ivory & Navy', bg: '#f4f2ec', ink: '#1b2440', soft: '#5a6178', accent: '#c2452e', dark: false },
  { id: 'sage', label: 'Sage', bg: '#eef0e4', ink: '#22301f', soft: '#5f6d59', accent: '#8a5a2e', dark: false },
  { id: 'midnight', label: 'Midnight', bg: '#101322', ink: '#f2ecdd', soft: '#9aa0b8', accent: '#e8b04b', dark: true },
  { id: 'deep-forest', label: 'Deep Forest', bg: '#0e1a14', ink: '#eef3e4', soft: '#8fa393', accent: '#d98f4e', dark: true },
  { id: 'plum-neon', label: 'Plum Neon', bg: '#160b1f', ink: '#fff4fa', soft: '#a58fb8', accent: '#ff4d9d', dark: true },
  { id: 'ocean-glow', label: 'Ocean Glow', bg: '#071620', ink: '#e9f6ff', soft: '#7fa3b8', accent: '#4dd4ff', dark: true },
  { id: 'crimson-gold', label: 'Crimson & Gold', bg: '#1c0d10', ink: '#f7ecdc', soft: '#a88f85', accent: '#e0a83c', dark: true },
] as const;

export interface FontOption {
  id: string;
  label: string;
  /** Headline and verse face. */
  display: string;
  /** Caption and UI face. */
  body: string;
  /** Small compensation so different faces sit at similar optical size. */
  scaleAdjust: number;
}

/**
 * Every family here is OFL and self-hosted in /public/fonts — Path B renders
 * offline, so a CDN reference would silently fall back to a system face.
 *
 * Complex scripts override the display face per-script inside the template
 * (there is no Devanagari Archivo Black, and faking one breaks conjuncts), so
 * a font choice never sacrifices correct shaping.
 */
export const FONTS: readonly FontOption[] = [
  { id: 'fraunces', label: 'Serif', display: "'Fraunces', Georgia, serif", body: "'Inter', system-ui, sans-serif", scaleAdjust: 1 },
  { id: 'archivo', label: 'Poster', display: "'Archivo Black', 'Inter', sans-serif", body: "'Inter', system-ui, sans-serif", scaleAdjust: 0.86 },
  { id: 'grotesk', label: 'Modern', display: "'Space Grotesk', 'Inter', sans-serif", body: "'Space Grotesk', system-ui, sans-serif", scaleAdjust: 0.95 },
  { id: 'inter', label: 'Clean', display: "'Inter', system-ui, sans-serif", body: "'Inter', system-ui, sans-serif", scaleAdjust: 0.94 },
] as const;

export interface SizeOption {
  id: string;
  label: string;
  /** Multiplier applied to the template's type scale. */
  scale: number;
}

export const SIZES: readonly SizeOption[] = [
  { id: 'compact', label: 'Compact', scale: 0.88 },
  { id: 'regular', label: 'Regular', scale: 1 },
  { id: 'bold', label: 'Large', scale: 1.14 },
] as const;

export interface BackgroundOption {
  id: string;
  label: string;
  /**
   * Which treatment the template applies. Most are CSS-generated; `photo`
   * layers a shipped licensed image with a slow Ken Burns drift and a
   * palette-tinted scrim so text stays legible on any theme.
   */
  kind:
    | 'plain'
    | 'grain'
    | 'mesh'
    | 'rays'
    | 'particles'
    | 'paper'
    | 'halftone'
    | 'linen'
    | 'photo'
    | 'video'
    | 'doodle';
  /** For kind 'photo', 'video' or 'doodle': root-relative asset path. */
  src?: string;
  /**
   * A small still of what this background actually looks like, shown in the
   * picker instead of the name.
   *
   * Sixty-nine of these now exist. A wall of words like "Halftone dots" and
   * "Groovy liquid" asks a creator to imagine each one and then click to find
   * out they guessed wrong; a wall of pictures asks them to point. The names
   * survive as tooltips and accessible labels, where they help rather than
   * substitute for looking.
   *
   * Generated by `scripts/make-bg-thumbs.ts` — the CSS treatments are
   * screenshotted from the real template rather than mocked up, so the
   * picture is the thing itself.
   */
  thumb?: string;
  /** Groups the picker draws a divider between. */
  group: 'texture' | 'doodle' | 'image' | 'video';
}

export const BACKGROUNDS: readonly BackgroundOption[] = [
  // CSS-generated: no image files, and they recolor with the palette.
  { id: 'plain', label: 'Plain', kind: 'plain', group: 'texture', thumb: '/backgrounds/thumbs/plain.jpg' },
  { id: 'grain', label: 'Soft grain', kind: 'grain', group: 'texture', thumb: '/backgrounds/thumbs/grain.jpg' },
  { id: 'mesh', label: 'Gradient mesh', kind: 'mesh', group: 'texture', thumb: '/backgrounds/thumbs/mesh.jpg' },
  { id: 'rays', label: 'Light rays', kind: 'rays', group: 'texture', thumb: '/backgrounds/thumbs/rays.jpg' },
  { id: 'particles', label: 'Particles', kind: 'particles', group: 'texture', thumb: '/backgrounds/thumbs/particles.jpg' },
  { id: 'paper', label: 'Paper texture', kind: 'paper', group: 'texture', thumb: '/backgrounds/thumbs/paper.jpg' },
  { id: 'halftone', label: 'Halftone dots', kind: 'halftone', group: 'texture', thumb: '/backgrounds/thumbs/halftone.jpg' },
  { id: 'linen', label: 'Linen weave', kind: 'linen', group: 'texture', thumb: '/backgrounds/thumbs/linen.jpg' },

  // Hand-drawn frames, authored in scripts/make-doodles.ts. Applied as an
  // alpha mask over a palette-ink layer, so they recolor with the theme.
  { id: 'doodle-faith', label: 'Faith margins', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-faith.svg', thumb: '/backgrounds/thumbs/doodle-faith.jpg' },
  { id: 'doodle-garden', label: 'Garden frame', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-garden.svg', thumb: '/backgrounds/thumbs/doodle-garden.jpg' },
  { id: 'doodle-shore', label: 'Sea of Galilee', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-shore.svg', thumb: '/backgrounds/thumbs/doodle-shore.jpg' },
  { id: 'doodle-dove', label: 'Doves & olive', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-dove.svg', thumb: '/backgrounds/thumbs/doodle-dove.jpg' },
  { id: 'doodle-dawn', label: 'Morning mercies', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-dawn.svg', thumb: '/backgrounds/thumbs/doodle-dawn.jpg' },
  { id: 'doodle-journey', label: 'Arrows & banners', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-journey.svg', thumb: '/backgrounds/thumbs/doodle-journey.jpg' },
  { id: 'doodle-lamp', label: 'Lamps & scrolls', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-lamp.svg', thumb: '/backgrounds/thumbs/doodle-lamp.jpg' },
  { id: 'doodle-heights', label: 'Mountains', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-heights.svg', thumb: '/backgrounds/thumbs/doodle-heights.jpg' },
  { id: 'doodle-table', label: 'Bread & cup', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-table.svg', thumb: '/backgrounds/thumbs/doodle-table.jpg' },
  { id: 'doodle-praise', label: 'Praise notes', kind: 'doodle', group: 'doodle', src: '/backgrounds/doodles/doodle-praise.svg', thumb: '/backgrounds/thumbs/doodle-praise.jpg' },

  // Licensed full-bleed images, cropped to 1080x1920 at import. Ken Burns
  // drift plus a palette-tinted scrim.
  { id: 'img-fluffy-sky', label: 'Fluffy sky', kind: 'photo', group: 'image', src: '/backgrounds/img/fluffy-sky.jpg', thumb: '/backgrounds/thumbs/img-fluffy-sky.jpg' },
  { id: 'img-tropical-sunset', label: 'Tropical sunset', kind: 'photo', group: 'image', src: '/backgrounds/img/tropical-sunset.jpg', thumb: '/backgrounds/thumbs/img-tropical-sunset.jpg' },
  { id: 'img-nebula', label: 'Nebula', kind: 'photo', group: 'image', src: '/backgrounds/img/nebula.jpg', thumb: '/backgrounds/thumbs/img-nebula.jpg' },
  { id: 'img-sun-rays', label: 'Sun rays', kind: 'photo', group: 'image', src: '/backgrounds/img/sun-rays.jpg', thumb: '/backgrounds/thumbs/img-sun-rays.jpg' },
  { id: 'img-stained-glass', label: 'Stained glass', kind: 'photo', group: 'image', src: '/backgrounds/img/stained-glass.jpg', thumb: '/backgrounds/thumbs/img-stained-glass.jpg' },
  { id: 'img-gold-leaf', label: 'Gold leaf', kind: 'photo', group: 'image', src: '/backgrounds/img/gold-leaf.jpg', thumb: '/backgrounds/thumbs/img-gold-leaf.jpg' },
  { id: 'img-golden-silk', label: 'Golden silk', kind: 'photo', group: 'image', src: '/backgrounds/img/golden-silk.jpg', thumb: '/backgrounds/thumbs/img-golden-silk.jpg' },
  { id: 'img-blue-marble', label: 'Blue marble', kind: 'photo', group: 'image', src: '/backgrounds/img/blue-marble.jpg', thumb: '/backgrounds/thumbs/img-blue-marble.jpg' },
  { id: 'img-wood-grain', label: 'Wood grain', kind: 'photo', group: 'image', src: '/backgrounds/img/wood-grain.jpg', thumb: '/backgrounds/thumbs/img-wood-grain.jpg' },
  { id: 'img-grunge-color', label: 'Color grunge', kind: 'photo', group: 'image', src: '/backgrounds/img/grunge-color.jpg', thumb: '/backgrounds/thumbs/img-grunge-color.jpg' },
  { id: 'img-halftone-pop', label: 'Halftone pop', kind: 'photo', group: 'image', src: '/backgrounds/img/halftone-pop.jpg', thumb: '/backgrounds/thumbs/img-halftone-pop.jpg' },
  { id: 'img-groovy-liquid', label: 'Groovy liquid', kind: 'photo', group: 'image', src: '/backgrounds/img/groovy-liquid.jpg', thumb: '/backgrounds/thumbs/img-groovy-liquid.jpg' },
  { id: 'img-rainbow-glitter', label: 'Rainbow glitter', kind: 'photo', group: 'image', src: '/backgrounds/img/rainbow-glitter.jpg', thumb: '/backgrounds/thumbs/img-rainbow-glitter.jpg' },
  { id: 'img-confetti', label: 'Confetti', kind: 'photo', group: 'image', src: '/backgrounds/img/confetti.jpg', thumb: '/backgrounds/thumbs/img-confetti.jpg' },
  { id: 'img-geo-pattern', label: 'Geometric', kind: 'photo', group: 'image', src: '/backgrounds/img/geo-pattern.jpg', thumb: '/backgrounds/thumbs/img-geo-pattern.jpg' },
  { id: 'img-floral-pattern', label: 'Floral', kind: 'photo', group: 'image', src: '/backgrounds/img/floral-pattern.jpg', thumb: '/backgrounds/thumbs/img-floral-pattern.jpg' },
  { id: 'img-harvest', label: 'Harvest', kind: 'photo', group: 'image', src: '/backgrounds/img/harvest.jpg', thumb: '/backgrounds/thumbs/img-harvest.jpg' },

  // Animated loops, normalized by scripts/import-video-backgrounds.mjs:
  // audio stripped, tail cross-faded over the head so the loop has no
  // visible cut, poster taken past the cross-fade.
  { id: 'video-still-waters', label: 'Still waters', kind: 'video', group: 'video', src: '/backgrounds/video/still-waters.mp4', thumb: '/backgrounds/video/still-waters.jpg' },
  { id: 'video-forest-path', label: 'Forest path', kind: 'video', group: 'video', src: '/backgrounds/video/forest-path.mp4', thumb: '/backgrounds/video/forest-path.jpg' },
  { id: 'video-sparks', label: 'Sparks', kind: 'video', group: 'video', src: '/backgrounds/video/sparks.mp4', thumb: '/backgrounds/video/sparks.jpg' },
  { id: 'video-mossy-forest', label: 'Mossy forest', kind: 'video', group: 'video', src: '/backgrounds/video/mossy-forest.mp4', thumb: '/backgrounds/video/mossy-forest.jpg' },
  { id: 'video-blossom-path', label: 'Blossom path', kind: 'video', group: 'video', src: '/backgrounds/video/blossom-path.mp4', thumb: '/backgrounds/video/blossom-path.jpg' },
  { id: 'video-raindrops', label: 'Raindrops', kind: 'video', group: 'video', src: '/backgrounds/video/raindrops.mp4', thumb: '/backgrounds/video/raindrops.jpg' },
  { id: 'video-ice-cave', label: 'Ice cave', kind: 'video', group: 'video', src: '/backgrounds/video/ice-cave.mp4', thumb: '/backgrounds/video/ice-cave.jpg' },
  { id: 'video-dunes', label: 'Dunes', kind: 'video', group: 'video', src: '/backgrounds/video/dunes.mp4', thumb: '/backgrounds/video/dunes.jpg' },
  { id: 'video-crystals', label: 'Crystals', kind: 'video', group: 'video', src: '/backgrounds/video/crystals.mp4', thumb: '/backgrounds/video/crystals.jpg' },
  { id: 'video-bamboo', label: 'Bamboo', kind: 'video', group: 'video', src: '/backgrounds/video/bamboo.mp4', thumb: '/backgrounds/video/bamboo.jpg' },
  { id: 'video-ink-water', label: 'Ink in water', kind: 'video', group: 'video', src: '/backgrounds/video/ink-water.mp4', thumb: '/backgrounds/video/ink-water.jpg' },
  { id: 'video-rainy-window', label: 'Rainy window', kind: 'video', group: 'video', src: '/backgrounds/video/rainy-window.mp4', thumb: '/backgrounds/video/rainy-window.jpg' },
  { id: 'video-aurora', label: 'Aurora', kind: 'video', group: 'video', src: '/backgrounds/video/aurora.mp4', thumb: '/backgrounds/video/aurora.jpg' },
  { id: 'video-smoke', label: 'Smoke', kind: 'video', group: 'video', src: '/backgrounds/video/smoke.mp4', thumb: '/backgrounds/video/smoke.jpg' },
  { id: 'video-underwater', label: 'Underwater', kind: 'video', group: 'video', src: '/backgrounds/video/underwater.mp4', thumb: '/backgrounds/video/underwater.jpg' },
  { id: 'video-flower-field', label: 'Flower field', kind: 'video', group: 'video', src: '/backgrounds/video/flower-field.mp4', thumb: '/backgrounds/video/flower-field.jpg' },
  { id: 'video-snowy-pines', label: 'Snowy pines', kind: 'video', group: 'video', src: '/backgrounds/video/snowy-pines.mp4', thumb: '/backgrounds/video/snowy-pines.jpg' },
  { id: 'video-bubbles', label: 'Bubbles', kind: 'video', group: 'video', src: '/backgrounds/video/bubbles.mp4', thumb: '/backgrounds/video/bubbles.jpg' },
  { id: 'video-calm-sea', label: 'Calm sea', kind: 'video', group: 'video', src: '/backgrounds/video/calm-sea.mp4', thumb: '/backgrounds/video/calm-sea.jpg' },
  { id: 'video-above-clouds', label: 'Above the clouds', kind: 'video', group: 'video', src: '/backgrounds/video/above-clouds.mp4', thumb: '/backgrounds/video/above-clouds.jpg' },
  { id: 'video-gold-kaleidoscope', label: 'Gold kaleidoscope', kind: 'video', group: 'video', src: '/backgrounds/video/gold-kaleidoscope.mp4', thumb: '/backgrounds/video/gold-kaleidoscope.jpg' },
  { id: 'video-rising-bubbles', label: 'Rising bubbles', kind: 'video', group: 'video', src: '/backgrounds/video/rising-bubbles.mp4', thumb: '/backgrounds/video/rising-bubbles.jpg' },
  { id: 'video-crystal-tunnel', label: 'Crystal tunnel', kind: 'video', group: 'video', src: '/backgrounds/video/crystal-tunnel.mp4', thumb: '/backgrounds/video/crystal-tunnel.jpg' },
  { id: 'video-starburst', label: 'Starburst', kind: 'video', group: 'video', src: '/backgrounds/video/starburst.mp4', thumb: '/backgrounds/video/starburst.jpg' },
  { id: 'video-sand-layers', label: 'Sand layers', kind: 'video', group: 'video', src: '/backgrounds/video/sand-layers.mp4', thumb: '/backgrounds/video/sand-layers.jpg' },
  { id: 'video-forest-rays', label: 'Forest rays', kind: 'video', group: 'video', src: '/backgrounds/video/forest-rays.mp4', thumb: '/backgrounds/video/forest-rays.jpg' },
  { id: 'video-falling-leaves', label: 'Falling leaves', kind: 'video', group: 'video', src: '/backgrounds/video/falling-leaves.mp4', thumb: '/backgrounds/video/falling-leaves.jpg' },
  { id: 'video-light-spiral', label: 'Light spiral', kind: 'video', group: 'video', src: '/backgrounds/video/light-spiral.mp4', thumb: '/backgrounds/video/light-spiral.jpg' },
  { id: 'video-dewdrops', label: 'Dewdrops', kind: 'video', group: 'video', src: '/backgrounds/video/dewdrops.mp4', thumb: '/backgrounds/video/dewdrops.jpg' },
  { id: 'video-neon-portal', label: 'Neon portal', kind: 'video', group: 'video', src: '/backgrounds/video/neon-portal.mp4', thumb: '/backgrounds/video/neon-portal.jpg' },
  { id: 'video-feathers', label: 'Feathers', kind: 'video', group: 'video', src: '/backgrounds/video/feathers.mp4', thumb: '/backgrounds/video/feathers.jpg' },
  { id: 'video-autumn-path', label: 'Autumn path', kind: 'video', group: 'video', src: '/backgrounds/video/autumn-path.mp4', thumb: '/backgrounds/video/autumn-path.jpg' },
  { id: 'video-blossom-tunnel', label: 'Blossom tunnel', kind: 'video', group: 'video', src: '/backgrounds/video/blossom-tunnel.mp4', thumb: '/backgrounds/video/blossom-tunnel.jpg' },
  { id: 'video-cloud-vortex', label: 'Cloud vortex', kind: 'video', group: 'video', src: '/backgrounds/video/cloud-vortex.mp4', thumb: '/backgrounds/video/cloud-vortex.jpg' },
] as const;

export interface TextStyleOption {
  id: string;
  label: string;
  blurb: string;
}

/**
 * How stage text ENTERS — the device line, the teaching words, the
 * verse/citation panel. A style is a motion recipe, never a clock: each
 * template keeps its own timing (kinetic words still land on the voice) and
 * its seam transitions. `signature` is the template's designed move, so
 * existing specs render unchanged. Captions are deliberately not covered —
 * their hard cuts are a legibility decision, not a style.
 *
 * The id travels as `data-anim` on the composition root; templates hold the
 * matching GSAP recipe inline (transform/opacity/filter only, seek-safe).
 */
export const TEXT_STYLES: readonly TextStyleOption[] = [
  { id: 'signature', label: 'Signature', blurb: "Each style's designed move" },
  { id: 'floating', label: 'Floating', blurb: 'Rises softly with a touch of blur' },
  { id: 'dropping', label: 'Dropping', blurb: 'Falls in and settles with a bounce' },
  { id: 'sliding', label: 'Sliding', blurb: 'Enters from the side' },
  { id: 'pop', label: 'Pop', blurb: 'Scales up with a snap' },
  { id: 'typewriter', label: 'Typewriter', blurb: 'Appears in place, no motion' },
  { id: 'flip', label: 'Flip', blurb: 'Flap-board rotation' },
  { id: 'blur-focus', label: 'Blur focus', blurb: 'Racks into focus from a blur' },
] as const;

export interface MusicOption {
  id: string;
  label: string;
  /** Empty for silence. */
  file: string;
  credit: string;
}

/**
 * Music beds, pre-attenuated and faded at import time with ffmpeg, so the
 * mix is right no matter what a player does with volume attributes.
 *
 * Every track here is licensed to the project creator through Audiio and
 * requires NO attribution. The four CC-BY tracks this set opened with were
 * removed deliberately: a short is made to be reposted, and a licence whose
 * terms depend on a credit line surviving that repost is a licence the
 * creator will breach without ever knowing. The credit still travels with the
 * gallery entry, as a courtesy rather than an obligation.
 */
export const MUSIC: readonly MusicOption[] = [
  { id: 'none', label: 'No music', file: '', credit: '' },
  { id: 'right-here', label: 'Right Here', file: '/music/right-here.mp3', credit: '"Right Here" Su — Audiio license' },
  { id: 'deeper-still', label: 'Deeper Still', file: '/music/deeper-still.mp3', credit: '"Deeper Still" Jacob Montague — Audiio license' },
  { id: 'beyond-the-pull', label: 'Ambient Drift', file: '/music/beyond-the-pull.mp3', credit: '"Beyond the Pull of Things (Ambient)" Dmitriy Redko — Audiio license' },
  { id: 'eternal-strings', label: 'Eternal Strings', file: '/music/eternal-strings.mp3', credit: '"Eternal (Hanging Solo with Strings)" Pendelton — Audiio license' },
  { id: 'sleep-habits', label: 'Gentle Sleep', file: '/music/sleep-habits.mp3', credit: '"Sleep Habits" Allen Bright — Audiio license' },
  { id: 'elevate', label: 'Elevate', file: '/music/elevate.mp3', credit: '"Elevate (Instrumental)" JinSei — Audiio license' },
  { id: 'snow-fall', label: 'Snow Fall', file: '/music/snow-fall.mp3', credit: '"Snow Fall (Instrumental)" Nylon & Cedar — Audiio license' },
  { id: 'o-holy-night', label: 'O Holy Night', file: '/music/o-holy-night.mp3', credit: '"O Holy Night (Instrumental)" Allen & Bright — Audiio license' },
  { id: 'christmas-cassette', label: 'Christmas Cassette', file: '/music/christmas-cassette.mp3', credit: '"Christmas on Cassette (Instrumental)" Alex Velte — Audiio license' },
] as const;

/** The theme a spec carries. Every field optional; templates have defaults. */
export interface ShortTheme {
  paletteId?: string;
  fontId?: string;
  sizeId?: string;
  backgroundId?: string;
  /** How stage text enters; 'signature' keeps the template's designed move. */
  textStyleId?: string;
  /** 'off' hides the caption rail; the verse and reference always render. */
  captions?: 'on' | 'off';
  musicId?: string;
}

export function resolveMusic(theme: ShortTheme | undefined): MusicOption {
  return MUSIC.find((m) => m.id === theme?.musicId) ?? MUSIC[0];
}

export interface ResolvedTheme {
  palette: PaletteOption;
  font: FontOption;
  size: SizeOption;
  background: BackgroundOption;
}

export function resolveTheme(theme: ShortTheme | undefined): ResolvedTheme {
  return {
    palette: PALETTES.find((p) => p.id === theme?.paletteId) ?? PALETTES[0],
    font: FONTS.find((f) => f.id === theme?.fontId) ?? FONTS[0],
    size: SIZES.find((s) => s.id === theme?.sizeId) ?? SIZES[1],
    background:
      BACKGROUNDS.find((b) => b.id === theme?.backgroundId) ?? BACKGROUNDS[1],
  };
}

/**
 * The inline style written onto the composition root. Inline, not a <style>
 * block, so it survives any template's own CSS unchanged and wins the cascade
 * exactly where intended: custom properties only.
 */
export function themeStyle(theme: ShortTheme | undefined): string {
  // The background is deliberately absent: it resolves to an ATTRIBUTE
  // (`data-bg`) plus an asset URL, both written by the bake step, not to a
  // custom property. See `themeAttributes`.
  const { palette, font, size } = resolveTheme(theme);
  return [
    `--t-bg: ${palette.bg}`,
    `--t-ink: ${palette.ink}`,
    `--t-soft: ${palette.soft}`,
    `--t-accent: ${palette.accent}`,
    `--t-dark: ${palette.dark ? 1 : 0}`,
    `--t-font-display: ${font.display}`,
    `--t-font-body: ${font.body}`,
    `--t-scale: ${(size.scale * font.scaleAdjust).toFixed(3)}`,
  ].join('; ');
}

export function themeAttributes(theme: ShortTheme | undefined): {
  bg: string;
  dark: '1' | '0';
  /** Root-relative photo path, when the background is a photo. */
  photoSrc?: string;
  /** Root-relative video path, when the background is an animated loop. */
  videoSrc?: string;
  /**
   * Doodle SVG as a data URI, when the background is a doodle frame. A data
   * URI, not a path: mask-image loads are CORS-checked, and the offline
   * renderer serves compositions from file:// where external masks are
   * blocked. Data URIs are scheme-exempt, so preview and render agree.
   */
  doodleData?: string;
  /** Resolved text-motion id; unknown ids fall back to 'signature'. */
  textStyle: string;
  captionsOff: boolean;
} {
  const { palette, background } = resolveTheme(theme);
  return {
    bg: background.kind,
    dark: palette.dark ? '1' : '0',
    photoSrc: background.kind === 'photo' ? background.src : undefined,
    videoSrc: background.kind === 'video' ? background.src : undefined,
    doodleData:
      background.kind === 'doodle' ? DOODLE_DATA[background.id] : undefined,
    textStyle:
      TEXT_STYLES.find((t) => t.id === theme?.textStyleId)?.id ?? 'signature',
    captionsOff: theme?.captions === 'off',
  };
}
