import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Scriptorium",
  description: "Scripture shorts, in your own language. Verse text retrieved from YouVersion, never generated.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* The same generated stylesheet the compositions link. Scoped by
            unicode-range, so the studio downloads only the subsets its own
            chrome actually draws — and a passage previewed in Telugu or
            Hebrew has its face already declared.

            Linked rather than imported, and the lint rule is waived rather
            than worked around: this file is generated by
            `scripts/fetch-script-fonts.mjs` into `public/`, because the frozen
            compositions are plain HTML with no bundler and must be able to
            link it too. Pulling it through the CSS pipeline here would give
            the app one copy and the templates another, and the two would drift
            — which is the exact failure this replaced. */}
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel="stylesheet" href="/fonts/fonts.css" />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
