/**
 * Audit the language registry against the live YouVersion Platform API.
 *
 *   npm run audit:languages
 *
 * Answers, with evidence rather than assertion, the question the whole project
 * rests on: in how many languages can this actually produce a finished short?
 *
 * A language only counts when all three hold:
 *   - YouVersion serves a Bible version to THIS app key (so we may render it)
 *   - a free neural voice exists (Speechmatics for English, Piper otherwise)
 *   - Speechmatics can transcribe it, giving measured word timing
 *
 * Writes `docs/language-coverage.md` so the claim in the README and the writeup
 * is generated from a real API sweep, not from a spreadsheet someone typed.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { LANGUAGES, tierOf } from '@/lib/languages/registry';
import { YouVersionClient } from '@/lib/scripture/youversion';

interface Row {
  code: string;
  name: string;
  nativeName: string;
  tier: string;
  versions: number;
  sample?: string;
  voice: boolean;
  asr: boolean;
}

async function main() {
  const client = new YouVersionClient();
  const rows: Row[] = [];

  for (const entry of LANGUAGES) {
    let versions = 0;
    let sample: string | undefined;

    try {
      const bibles = await client.listBibles(entry.code);
      versions = bibles.length;
      if (bibles[0]) {
        sample = `${bibles[0].abbreviation} — ${bibles[0].title}`;
      }
    } catch (error) {
      process.stderr.write(
        `  ${entry.code}: lookup failed (${(error as Error).message.slice(0, 80)})\n`,
      );
    }

    rows.push({
      code: entry.code,
      name: entry.name,
      nativeName: entry.nativeName,
      tier: tierOf(entry),
      versions,
      sample,
      voice: Boolean(entry.piperVoice) || entry.code === 'en',
      asr: Boolean(entry.asrCode),
    });

    process.stdout.write(
      `${entry.code.padEnd(4)} ${entry.name.padEnd(14)} ` +
        `${String(versions).padStart(3)} version(s)  ` +
        `${entry.piperVoice || entry.code === 'en' ? 'voice' : '     '}  ` +
        `${entry.asrCode ? 'timing' : '      '}\n`,
    );
  }

  const complete = rows.filter((r) => r.versions > 0 && r.voice && r.asr);
  const voiced = rows.filter((r) => r.versions > 0 && r.voice && !r.asr);
  const textOnly = rows.filter((r) => r.versions > 0 && !r.voice);
  const noBible = rows.filter((r) => r.versions === 0);

  console.log('\n================ coverage ================');
  console.log(`registry languages          : ${rows.length}`);
  console.log(`with a licensed Bible       : ${rows.length - noBible.length}`);
  console.log(`complete (text+voice+timing): ${complete.length}`);
  console.log(`voiced, estimated timing    : ${voiced.length}`);
  console.log(`captions only               : ${textOnly.length}`);
  console.log(`no Bible for this app key   : ${noBible.length}`);
  console.log(
    `total Bible versions reachable: ${rows.reduce((n, r) => n + r.versions, 0)}`,
  );

  const md = [
    '# Language coverage',
    '',
    'Generated by `npm run audit:languages`, which queries the live YouVersion',
    'Platform API for every language in the registry. Counts below are what this',
    "app key is actually licensed for — not what the platform holds in total.",
    '',
    `- **${complete.length} languages complete**: licensed Bible text, a free neural voice, and word timing measured from the audio.`,
    `- **${voiced.length} voiced**: text and voice, with caption timing estimated from word length.`,
    `- **${textOnly.length} captions only**: text, no free voice model exists yet.`,
    `- **${rows.reduce((n, r) => n + r.versions, 0)} Bible versions** reachable in total.`,
    '',
    '| Language | Code | Versions | Voice | Measured timing | Sample version |',
    '| --- | --- | --: | :-: | :-: | --- |',
    ...rows.map(
      (r) =>
        `| ${r.nativeName} (${r.name}) | \`${r.code}\` | ${r.versions} | ` +
        `${r.voice ? 'yes' : 'no'} | ${r.asr ? 'yes' : 'no'} | ${r.sample ?? '—'} |`,
    ),
    '',
  ].join('\n');

  mkdirSync('docs', { recursive: true });
  writeFileSync('docs/language-coverage.md', md, 'utf8');

  // Machine-readable form, committed and read by the app so the number shown
  // to users is the audited one rather than an optimistic registry count.
  writeFileSync(
    'src/lib/languages/coverage.generated.json',
    `${JSON.stringify(
      {
        auditedAt: new Date().toISOString().slice(0, 10),
        complete: complete.length,
        voiced: voiced.length,
        textOnly: textOnly.length,
        withBible: rows.length - noBible.length,
        totalVersions: rows.reduce((n, r) => n + r.versions, 0),
        versionsByLanguage: Object.fromEntries(
          rows.map((r) => [r.code, r.versions]),
        ),
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  console.log(
    '\nwrote docs/language-coverage.md and src/lib/languages/coverage.generated.json',
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
