/**
 * Write docs/doodle-library.md from the panel catalogue.
 *
 *   npm run doodles:doc
 *
 * Generated rather than hand-maintained so the document cannot drift from the
 * data the matcher actually uses — a description that is right in the docs and
 * wrong in the code is worse than no document.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { DOODLE_PANELS, MIN_BAND, type DoodlePanel } from '@/lib/visuals/doodles';

const SERIES: Record<string, { title: string; note: string }> = {
  peter: {
    title: 'Peter on the water — Matthew 14',
    note: 'Night sea in blue and purple crayon, a smiling moon, Jesus in white. Six panels, a wide clean band on all but the sinking shot.',
  },
  donkey: {
    title: 'Balaam’s donkey — Numbers 22',
    note: 'A walled vineyard lane under a smiling sun, an angel with a drawn blue sword. Two panels carry shouted speech bubbles.',
  },
  genesis22: {
    title: 'Abraham and Isaac — Genesis 22',
    note: 'Purple-grey mountain rock and gold sunrise, resolving to a cross and a temple. Wide clean band throughout.',
  },
  prodigal: {
    title: 'The prodigal son — Luke 15',
    note: 'A golden wheat road with a heart-and-swirl border. Seven panels, the fullest arc in the set, and a 28% band on every one.',
  },
  job38: {
    title: 'Job 38',
    note: 'Deckle-edged paper under an enormous cosmic swirl. Full-bleed, and every panel carries a drawn label.',
  },
  psalm22: {
    title: 'Psalm 22',
    note: 'A spiral-notebook page: a storm over a dark peak, a singer with a lyre, resolving to a hand of light.',
  },
  rev20: {
    title: 'Revelation 20',
    note: 'A sleeping rainbow dragon in chains and a blond angel with a key, on notebook paper. Banner headings on most panels.',
  },
  ecc311: {
    title: 'Ecclesiastes 3:11 — eternity in the heart',
    note: 'Torn-edge paper, a boy with an infinity emblem, crayon sunsets. The most reusable series for general longing/searching teachings.',
  },
  wordstudy: {
    title: 'The charcoal fire — John 21',
    note: 'A pink sunrise shore with a flame border: denial, breakfast, restoration.',
  },
  panels: {
    title: 'Doors of insight',
    note: 'A backpacked boy walking through brightly outlined doors. Every panel carries a handwritten caption.',
  },
};

function table(panels: DoodlePanel[]): string {
  const rows = panels.map((p) => {
    const band = p.band >= MIN_BAND ? `${p.band}%` : `${p.band}% *`;
    const text = p.hasText ? 'yes' : '—';
    return `| \`${p.id}\` | ${p.description} | ${p.tags.join(', ')} | ${band} | ${text} |`;
  });
  return [
    '| Panel | What is on it | Match tags | Band | Baked-in text |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

const byTopic = new Map<string, DoodlePanel[]>();
for (const panel of DOODLE_PANELS) {
  const list = byTopic.get(panel.topic) ?? [];
  list.push(panel);
  byTopic.set(panel.topic, list);
}

const withText = DOODLE_PANELS.filter((p) => p.hasText).length;
const wideBand = DOODLE_PANELS.filter((p) => p.band >= MIN_BAND).length;

const doc = `<!-- Generated by scripts/doodle-catalog.ts — do not edit by hand. -->

# The doodle panel library

${DOODLE_PANELS.length} hand-drawn vertical panels (1080×1935) shipped in
\`public/doodles\`, catalogued in \`src/lib/visuals/doodles.ts\`. They are the
house style for AI-visual mode: a creator who picks **AI images** gets a panel
from here whenever one honestly fits the teaching, and Grok only draws when
nothing does.

**Why reuse first.** A shipped panel is instant, costs nothing, and — unlike a
generation — is a frame someone has already looked at and approved. Reuse is
not the cheap path here, it is the reliable one.

## How a panel gets picked

\`matchDoodle()\` scores every panel against the teaching:

- a hit on the model's own \`visualTerms\` scores **3**
- a hit on a noun merely present in the authored English text scores **1** —
  a weak signal by design, and empty in a non-English short, so a panel has to
  be earned by \`visualTerms\` alone there
- \`+0.5\` for no baked-in text, \`+0.25\` for a band at or above ${MIN_BAND}%

Below a score of 3 there is no match and Grok is asked instead. A panel that
does not fit is worse than no panel: a wrong picture actively misteaches.
Scoring is deterministic and ties break on panel id, so the same teaching
always resolves to the same panel — which the render contract requires, and
which also means re-running a short returns the picture the creator approved.

## Layout metrics

Two numbers per panel, measured from the pixels rather than guessed
(\`scripts/measure-doodle-bands.py\`):

- **Band** — how far down the panel the paper stays clean across the centre
  column, where the sentence sits. The template lays a scrim of the panel's own
  paper colour over \`max(band, ${MIN_BAND}%)\`, so on a panel that already
  reserves a clean upper quarter the scrim is invisible, and on a full-bleed
  one it manufactures the band. Rows marked \`*\` are full-bleed and rely on
  the manufactured band.
- **Paper** — the page stock, sampled from the panel's top edge, so that scrim
  seam cannot be seen.

${wideBand} of ${DOODLE_PANELS.length} panels have a natural band of ${MIN_BAND}% or more.

## Baked-in text

${withText} panels have English words drawn into the art — banners, speech
bubbles, handwritten captions. They stay eligible, because the set is small and
each panel earns its place, but the matcher breaks ties against them: English
lettering under a Hindi sentence reads as a mistake. Prefer a text-free panel
when both fit.

---

${[...byTopic.entries()]
  .map(([topic, panels]) => {
    const meta = SERIES[topic] ?? { title: topic, note: '' };
    return `## ${meta.title}\n\n\`public/doodles/${topic}/\` · paper \`${panels[0].paper}\`\n\n${meta.note}\n\n${table(panels)}`;
  })
  .join('\n\n')}
`;

const out = join(process.cwd(), 'docs', 'doodle-library.md');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, doc, 'utf8');
console.log(`wrote ${out} (${DOODLE_PANELS.length} panels)`);
